// The whole build, and there is no bundler around it: esbuild reads the
// TypeScript, resolves `@/…` from tsconfig's own `paths`, bundles, minifies and
// writes the sourcemap — five rollup plugins' worth of work in one call, and
// roughly a hundredth of the time (37 ms against 3.7 s).
//
// What it does NOT do is TYPE CHECK: esbuild erases types without ever looking
// at them, so `npm run build` runs `tsc --noEmit` first (see package.json) — a
// build that never checks a type would wave a broken file through in silence.
import esbuild from 'esbuild';
import { copyFileSync, mkdirSync, readFileSync, watch } from 'node:fs';

const isProd = process.argv.includes('--prod');
const isWatch = process.argv.includes('--watch');

// `dist/` IS the plugin: main.js, manifest.json, styles.css. The project root
// holds sources only.
const OUT_DIR = 'dist';
const CSS_SOURCE = 'styles.css';
const MANIFEST = 'manifest.json';

const kb = (n) => (n / 1024).toFixed(1);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
https://github.com/aisahpA/obsidian-position-restore
*/
`;

const js = {
	entryPoints: ['src/main.ts'],
	outfile: `${OUT_DIR}/main.js`,
	bundle: true,
	format: 'cjs',
	platform: 'browser',
	// tsconfig's own target, and the one Obsidian's own sample plugin ships.
	// Measured against es2019: 4.2 kB smaller (1.2 kB gzipped) — `??`, `?.` and
	// class fields stop being rewritten into their ES2019 equivalents, and
	// nothing this plugin supports (minAppVersion 1.13) runs anything older.
	target: 'es2021',
	// What Obsidian hands the plugin at runtime, so it must not be bundled: a
	// second copy of CodeMirror or Lezer would be a DIFFERENT instance than the
	// app's, and the two would not share state.
	//
	// `electron` and node's built-ins are deliberately NOT on this list, though
	// the sample plugin lists them: this plugin ships to phones as well (see
	// manifest's `isDesktopOnly: false`), where neither of them exists — so a
	// stray `import { clipboard } from 'electron'` should fail the BUILD,
	// loudly, instead of quietly becoming a `require` that only breaks on a
	// device.
	external: ['obsidian', '@codemirror/*', '@lezer/*'],
	minify: isProd,
	sourcemap: isProd ? false : 'inline',
	banner: { js: banner },
	// Obsidian is handed the plugin class ITSELF: that is what rollup's
	// `exports: 'default'` used to leave in `module.exports`, and esbuild's CJS
	// output would hand it an object with a single `default` key instead. This
	// one line is what keeps the two builds interchangeable.
	footer: { js: 'module.exports = module.exports.default || module.exports;' },
	logLevel: 'info',
};

// The stylesheet: minified in a prod build, and COPIED in a dev one. esbuild
// drops CSS comments either way (measured: all 73 of them), and those comments
// say why a rule exists — which is exactly what a reader wants to find in
// devtools while working on one.
async function writeStyles() {
	const before = readFileSync(CSS_SOURCE, 'utf8');
	if (isProd) {
		await esbuild.build({
			entryPoints: [CSS_SOURCE],
			outfile: `${OUT_DIR}/${CSS_SOURCE}`,
			bundle: false,
			minify: true,
			sourcemap: false,
			logLevel: 'warning',
		});
	} else {
		copyFileSync(CSS_SOURCE, `${OUT_DIR}/${CSS_SOURCE}`);
	}
	const after = readFileSync(`${OUT_DIR}/${CSS_SOURCE}`, 'utf8');
	const saved = Math.round((1 - after.length / before.length) * 100);
	console.log(`${CSS_SOURCE} → ${OUT_DIR}/${CSS_SOURCE} (${kb(before.length)} kB → ${kb(after.length)} kB, −${saved}%)`);
}

function writeManifest() {
	copyFileSync(MANIFEST, `${OUT_DIR}/${MANIFEST}`);
}

mkdirSync(OUT_DIR, { recursive: true });

if (isWatch) {
	const ctx = await esbuild.context(js);
	await ctx.watch();
	await writeStyles();
	writeManifest();
	// `ctx.watch()` follows the JS import graph, and neither the stylesheet nor
	// the manifest is part of it — so those two get a watcher of their own.
	watch(CSS_SOURCE, () => void writeStyles());
	watch(MANIFEST, () => writeManifest());
	console.log(`watching src/, ${CSS_SOURCE} and ${MANIFEST} …`);
} else {
	writeManifest();
	await writeStyles();
	await esbuild.build(js);
}
