// 整个构建就这一个文件，外面没有打包器：esbuild 读 TypeScript、按 tsconfig 自己的
// `paths` 解析 `@/…`、打包、压缩、写 sourcemap —— 五个 rollup 插件干的活一次调用
// 做完，耗时大约只有它们的一百分之一（37 ms 对 3.7 s）。
//
// 它**不**做的一件事是类型检查：esbuild 抹掉类型时压根不看它们一眼，所以
// `npm run build` 先跑 `tsc --noEmit`（见 package.json）—— 一个从不检查类型的构建
// 会把坏文件悄无声息地放过去。
import esbuild from 'esbuild';
import { copyFileSync, mkdirSync, readFileSync, watch } from 'node:fs';

const isProd = process.argv.includes('--prod');
const isWatch = process.argv.includes('--watch');

// `dist/` **就是**插件本身：main.js、manifest.json、styles.css。项目根只放源码。
const OUT_DIR = 'dist';
const CSS_SOURCE = 'styles.css';
const MANIFEST = 'manifest.json';

const kb = (n) => (n / 1024).toFixed(1);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
https://github.com/aisahpA/obsidian-position-restore
*/
`;

const js = {
	entryPoints: ['src/main.ts'],
	outfile: `${OUT_DIR}/main.js`,
	bundle: true,
	format: 'cjs',
	platform: 'browser',
	// 用 tsconfig 自己的 target，也是 Obsidian 官方示例插件用的那个。
	// 跟 es2019 实测对比：小 4.2 kB（gzip 后 1.2 kB）—— `??`、`?.` 和类字段不再被
	// 改写成 ES2019 的等价物，而这个插件支持的任何环境（minAppVersion 1.13）都不会
	// 跑更旧的东西。
	target: 'es2021',
	// Obsidian 在运行时就交给插件的东西，所以不能打进包里：CodeMirror 或 Lezer 的
	// 第二份副本会是跟 app 那个**不同**的实例，两者不共享状态。
	//
	// `electron` 和 node 的内建模块**故意**不在这个表里，虽然官方示例插件列了它们：
	// 这个插件也发到手机上（见 manifest 的 `isDesktopOnly: false`），而在手机上这两者
	// 都不存在 —— 于是一句走错的 `import { clipboard } from 'electron'` 应该让**构建**
	// 大声失败，而不是悄悄变成一句 `require`、只在真机上才炸。
	external: ['obsidian', '@codemirror/*', '@lezer/*'],
	minify: isProd,
	sourcemap: isProd ? false : 'inline',
	banner: { js: banner },
	// 交给 Obsidian 的是插件类**本身**：这正是当年 rollup 的 `exports: 'default'`
	// 留在 `module.exports` 里的东西，而 esbuild 的 CJS 输出会改交一个只带 `default`
	// 键的对象。就是这一行让两种构建可以互换。
	footer: { js: 'module.exports = module.exports.default || module.exports;' },
	logLevel: 'info',
};

// 样式表：生产构建压缩它，开发构建直接**拷贝**它。两条路 esbuild 都会丢掉 CSS
// 注释（实测：73 条全丢），而那些注释写的是「这条规则为什么存在」—— 正是改一条
// 规则的人想在 devtools 里找到的东西。
async function writeStyles() {
	const before = readFileSync(CSS_SOURCE, 'utf8');
	if (isProd) {
		await esbuild.build({
			entryPoints: [CSS_SOURCE],
			outfile: `${OUT_DIR}/${CSS_SOURCE}`,
			bundle: false,
			minify: true,
			sourcemap: false,
			logLevel: 'warning',
		});
	} else {
		copyFileSync(CSS_SOURCE, `${OUT_DIR}/${CSS_SOURCE}`);
	}
	const after = readFileSync(`${OUT_DIR}/${CSS_SOURCE}`, 'utf8');
	const saved = Math.round((1 - after.length / before.length) * 100);
	console.log(`${CSS_SOURCE} → ${OUT_DIR}/${CSS_SOURCE} (${kb(before.length)} kB → ${kb(after.length)} kB, −${saved}%)`);
}

function writeManifest() {
	copyFileSync(MANIFEST, `${OUT_DIR}/${MANIFEST}`);
}

mkdirSync(OUT_DIR, { recursive: true });

if (isWatch) {
	const ctx = await esbuild.context(js);
	await ctx.watch();
	await writeStyles();
	writeManifest();
	// `ctx.watch()` 跟的是 JS 的 import 图，而样式表和 manifest 都不在其中 ——
	// 所以这两个各配一个自己的 watcher。
	watch(CSS_SOURCE, () => void writeStyles());
	watch(MANIFEST, () => writeManifest());
	console.log(`watching src/, ${CSS_SOURCE} and ${MANIFEST} …`);
} else {
	writeManifest();
	await writeStyles();
	await esbuild.build(js);
}
