import typescript from '@rollup/plugin-typescript';
import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import terser from '@rollup/plugin-terser';
import alias from '@rollup/plugin-alias';
import { fileURLToPath } from 'node:url';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

// PROD=1 (set by `npm run build` via --environment) → production: minified, no sourcemap.
// Otherwise (`npm run dev`, reload.sh without prod arg) → dev: inline sourcemap in single main.js.
const isProd = process.env.PROD === '1';

export default {
  input: 'src/main.ts',
  output: {
    file: 'main.js',
    sourcemap: isProd ? false : 'inline',
    format: 'cjs',
    exports: 'default',
    banner,
  },
  treeshake: { moduleSideEffects: false },
  external: ['obsidian', /^@codemirror\//],
  plugins: [
    // '@/x' -> src/x, the same mapping tsconfig.json declares in `paths`
    // (Rollup does not read tsconfig paths, so it needs its own copy).
    // Keep it a regex: a bare '@' would also capture '@codemirror/...'.
    alias({
      entries: [
        { find: /^@\//, replacement: fileURLToPath(new URL('./src/', import.meta.url)) },
      ],
    }),
    typescript({
      declaration: false,
      declarationMap: false,
    }),
    nodeResolve({browser: true}),
    commonjs(),
    ...(isProd ? [terser()] : []),
  ]
};
